apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "argocd-mcp.fullname" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "argocd-mcp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "argocd-mcp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "argocd-mcp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "argocd-mcp.serviceAccountName" . }}
      {{- end }}
      securityContext:
        {{- toYaml (default .Values.defaultPodSecurityContext .Values.podSecurityContext) | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml (default .Values.defaultSecurityContext .Values.securityContext) | nindent 12 }}
          image: "{{ template "argocd-mcp.image" .Values.image }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "dist/index.js"
            - {{ .Values.transport | quote }}
          command: ["node"]
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            {{- if .Values.argocd.readOnly }}
            - name: MCP_READ_ONLY
              value: "true"
            {{- end }}
          envFrom:
            - secretRef:
                name: {{ .Values.argocd.credentialsSecret }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
