apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubernetes-mcp-server.fullname" . }}
  namespace: {{ include "kubernetes-mcp-server.namespace" . }}
  labels:
    {{- include "kubernetes-mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: sse-port
    - port: {{ .Values.service.mcpPort }}
      targetPort: {{ .Values.service.mcpTargetPort }}
      protocol: TCP
      name: mcp-port
  selector:
    {{- include "kubernetes-mcp-server.selectorLabels" . | nindent 4 }}
