{{- if .Values.applications.argocdMcp.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-mcp
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "12"
spec:
  destination:
    namespace: {{ .Values.global.namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  source: 
    path: charts/argocd-mcp
    repoURL: 'https://github.com/davidseve/llama-stack-example.git'
    targetRevision: {{ .Values.global.targetRevision | default "HEAD" }}
    helm:
      valueFiles:
      - ../../gitops/values-common.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
