{{- if .Values.applications.milvus.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: milvus
  labels:
    kubernetes.io/metadata.name: milvus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: milvus
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: milvus
  source:
    repoURL: 'https://github.com/davidseve/llama-stack-example.git'
    targetRevision: HEAD
    path: charts/milvus
    helm: 
      valueFiles: 
        - values.yaml        
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}

