{{- if .Values.applications.tempo.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  destination:
    namespace: {{ .Values.global.namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: charts/tempo
    repoURL: 'https://github.com/davidseve/llama-stack-example.git'
    targetRevision: {{ .Values.global.targetRevision | default "HEAD" }}
    helm:
      valueFiles:
      - ../../gitops/values-common.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
    syncOptions:
      - SkipDryRunOnMissingResource=true
{{- end }}
