---
apiVersion: v2
description: A Helm chart for deploying Grafana with LlamaStack observability dashboards
name: llama-stack-grafana
version: 0.1.0
home: https://github.com/rhoai-genaiops/genaiops-helmcharts
